### ISSUE TITLE
FR / Proposal Firmware password MGMT. 

### ISSUE THREAD

**Issue by gavinelder** [mdmdirector/mdmdirector#32]
# Proposal

The following is a high-level discussion for managing Firmware passwords via MDMDirector mainly to make sure there are no contentious points before the implementation of any features. 

### Secret Storage & Escrow 

The firmware password will be stored in the Postgres backend a double can occur both to the Postgres backend and an escrow server if one is provided, the reason for storage in the database is to allow the use of MicroMDM's `VerifyFirmwarePassword` Endpoint

### Random Password Generator.

Do we want to support some feature which automatically generates a random password per device, or if we're choosing to support a randomly generate passcode at all?

### Implentation UX 

Single API endpoint which accepts a UDID & a Firmware password such as the follows 

```
#!/bin/bash
# Configure firmware password on a device registered in micromdm by a given device by UDID with a supplied password
# Example:
#          ./tools/firmware_password $udid $pincode
#
source $MDMDIRECTOR_ENV_PATH
endpoint="firmware_password"
jq -n \
  --arg udid "$1" \
  --arg firmwarepasscode "$2"
  '.udids = [$udid]
  |.value = true
  |.push_now = true
  |.firmwarepassword = "[$firmwarepasscode]"
  '|\
  curl -u "mdmdirector:$API_TOKEN" -X POST "$SERVER_URL/$endpoint" -d@-

```

### Metrics

The following metrics would be exported

- The number of devices with Firmware passwords.
- The number of devices with managed firmware passwords.
- The number of devices with un-managed firmware password.
- The number of devices where the stored firmware password is != stored firmware password.

**Comment by grahamgilbert** [comment]
Okay, so I still don’t think firmware passwords are useful really, but I also have some concerns. 

- Storing passwords in the clear in the database doesn’t strike me as a good idea. At the very least the password should be sent to an escrow server and the escrow server should give the okay or not.
- I not sure if random passwords would be a good idea since these can be more complicated than mdm unlock pins. How complex should they be? How do we configure said complexity? It sounds like this would be making decisions that would be better handled elsewhere.

**Comment by grahamgilbert** [comment]
Ah, you have to send the password. I really don’t think it’s a good idea to store it in the clear. This all sounds like it should be managed outside of mdmdirector to be honest. I’m yet to be convinced it belongs here.
